export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";
export const CLEAR_AUTH_ERROR = "CLEAR_AUTH_ERROR";
export const CREATE_NEW_USER_FAILURE= 'CREATE_NEW_USER_FAILURE';
export const CREATE_NEW_USER_REQUEST= 'CREATE_NEW_USER_REQUEST';
export const CREATE_NEW_USER_SUCCESS= 'CREATE_NEW_USER_SUCCESS';
export const GET_USER_DATA_FAILURE= 'GET_USER_DATA_FAILURE';
export const GET_USER_DATA_REQUEST= 'GET_USER_DATA_REQUEST';
export const GET_USER_DATA_SUCCESS= 'GET_USER_DATA_SUCCESS';
export const GET_CURRENT_USER_DATA_FAILURE= 'GET_CURRENT_USER_DATA_FAILURE';
export const GET_CURRENT_USER_DATA_REQUEST= 'GET_CURRENT_USER_DATA_REQUEST';
export const GET_CURRENT_USER_DATA_SUCCESS= 'GET_CURRENT_USER_DATA_SUCCESS';
export const SENT_EMAIL_VERIFICATION_REQUEST = "SENT_EMAIL_VERIFICATION_REQUEST";
export const SENT_EMAIL_VERIFICATION_SUCCESS = "SENT_EMAIL_VERIFICATION_SUCCESS";
export const SENT_EMAIL_VERIFICATION_FAILURE = "SENT_EMAIL_VERIFICATION_FAILURE";
export const SEND_PASSWORD_RESET_EMAIL_REQUEST = "SEND_PASSWORD_RESET_EMAIL_REQUEST";
export const SEND_PASSWORD_RESET_EMAIL_SUCCESS = "SEND_PASSWORD_RESET_EMAIL_SUCCESS";
export const SEND_PASSWORD_RESET_EMAIL_FAILURE = "SEND_PASSWORD_RESET_EMAIL_FAILURE";









export const GET_TODOS_REQUEST = 'GET_TODOS';
export const GET_TODOS_SUCCESS = 'GET_TODOS_SUCCESS';
export const GET_TODOS_ERROR = 'GET_TODOS_ERROR';

export const GET_TODO_REQUEST = 'GET_TODO';
export const GET_TODO_SUCCESS = 'GET_TODO_SUCCESS';
export const GET_TODO_ERROR = 'GET_TODO_ERROR';

export const ADD_TODO_REQUEST = 'ADD_TODO';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_ERROR = 'ADD_TODO_ERROR';

export const TOGGLE_COMPLETE_TODO = 'TOGGLE_COMPLETE_TODO';
export const TOGGLE_COMPLETE_SUCCESS = 'TOGGLE_COMPLETE_SUCCESS';
export const TOGGLE_COMPLETE_ERROR = 'TOGGLE_COMPLETE_ERROR';

export const UPDATE_TODO_REQUEST = 'UPDATE_TODO';
export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS';
export const UPDATE_TODO_ERROR = 'UPDATE_TODO_ERROR';

export const DELETE_TODO_REQUEST = 'DELETE_TODO';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const DELETE_TODO_ERROR = 'DELETE_TODO_ERROR';

export const GET_TAGS = 'GET_TAGS';
export const GET_TAGS_SUCCESS = 'GET_TAGS_SUCCESS';
export const GET_TAGS_ERROR = 'GET_TAGS_ERROR';

export const SET_SEARCH = 'SET_SEARCH';
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const LOCATION_CHANGED = 'LOCATION_CHANGED';

export const SET_PAGINATION_PAGE = 'SET_PAGINATION_PAGE';
export const SET_PAGINATION_ITEMS = 'SET_PAGINATION_ITEMS';
export const SET_PAGINATION_SIZE = 'SET_PAGINATION_SIZE';
export const SET_PAGINATION_RESET = 'SET_PAGINATION_RESET';
export const ERROR_CODE_ACCOUNT_EXISTS =
  'auth/account-exists-with-different-credential';

export const ERROR_MSG_ACCOUNT_EXISTS = `
  An account with an E-Mail address to
  this social account already exists. Try to login from
  this account instead and associate your social accounts on
  your personal account page.
`;
export const ERROR_CODE_ACCOUNT_ALREADY_EXISTS = 'auth/email-already-in-use';
export const ERROR_MSG_ACCOUNT_ALREADY_EXISTS = `
An account with an E-Mail address is already exists. Try to login from
  this account instead.`;
export const ERROR_CODE_WRONG_PASSWORD = 'auth/wrong-password';
export const ERROR_MSG_WRONG_PASSWORD = `Wrong Password! \n Please try again`;
export const ERROR_CODE_TOO_MANY_ATTEMPTS = "auth/too-many-requests";
export const ERROR_MSG_TOO_MANY_ATTEMPTS = `Access to this account has been temporarily disabled due to many failed login attempts.\n You can immediately restore it by resetting your password or you can try again later.`
export const ERROR_CODE_INVALID_LOGIN_CREDS = "auth/invalid-login-credentials";
export const ERROR_MSG_INVALID_LOGIN_CREDS = `Email or Password wrong.! \n Please try again`
export const ERROR_CODE_MISSING_LOGIN_CREDS = "auth/missing-password";
export const ERROR_MSG_MISSING_LOGIN_CREDS = `Password Missing.! \n Please try again`
// Notifications

export const NOTIFICAIONS_REQUEST = "NOTIFICAIONS_REQUEST";
export const NOTIFICAIONS_SUCCESS = "NOTIFICAIONS_SUCCESS";
export const NOTIFICAIONS_FAILURE = "NOTIFICAIONS_FAILURE";
export const NOTIFICAION_BY_ID_REQUEST = "NOTIFICAION_BY_ID_REQUEST";
export const NOTIFICAION_BY_ID_SUCCESS = "NOTIFICAION_BY_ID_SUCCESS";
export const NOTIFICAION_BY_ID_FAILURE = "NOTIFICAION_BY_ID_FAILURE";

//Calendar 

export const ADD_EVENT_REQUEST = 'ADD_EVENT_REQUEST';
export const ADD_EVENT_SUCCESS = 'ADD_EVENT_SUCCESS';
export const ADD_EVENT_FAILURE = 'ADD_EVENT_FAILURE';

export const GET_ALL_EVENTS_REQUEST = 'GET_ALL_EVENTS_REQUEST';
export const GET_ALL_EVENTS_SUCCESS = 'GET_ALL_EVENTS_SUCCESS';
export const GET_ALL_EVENTS_FAILURE = 'GET_ALL_EVENTS_FAILURE';

export const EDIT_EVENT_REQUEST = 'EDIT_EVENT_REQUEST';
export const EDIT_EVENT_SUCCESS = 'EDIT_EVENT_SUCCESS';
export const EDIT_EVENT_FAILURE = 'EDIT_EVENT_FAILURE';

export const DELETE_EVENT_REQUEST = 'DELETE_EVENT_REQUEST';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';
export const DELETE_EVENT_FAILURE = 'DELETE_EVENT_FAILURE';

export const SET_DRAGGABLE_EVENTS = 'SET_DRAGGABLE_EVENTS';
export const SET_DRAGGABLE_EVENT = 'SET_DRAGGABLE_EVENT';
export const DELETE_DRAGGABLE_EVENT = 'DELETE_DRAGGABLE_EVENT';

// dashboard data types

export const FETCH_DASHBOARD_DATA_START = 'FETCH_DASHBOARD_DATA_START';
export const FETCH_DASHBOARD_DATA_SUCCESS = 'FETCH_DASHBOARD_DATA_SUCCESS';
export const FETCH_DASHBOARD_DATA_FAILURE = 'FETCH_DASHBOARD_DATA_FAILURE';

export const INCREMENT_PAGE_VIEW_START = 'INCREMENT_PAGE_VIEW_START';
export const INCREMENT_PAGE_VIEW_SUCCESS = 'INCREMENT_PAGE_VIEW_SUCCESS';
export const INCREMENT_PAGE_VIEW_FAILURE = 'INCREMENT_PAGE_VIEW_FAILURE';
export const FETCH_ROUTE_TO_PAGE_ID_START = 'FETCH_ROUTE_TO_PAGE_ID_START';
export const FETCH_ROUTE_TO_PAGE_ID_SUCCESS = 'FETCH_ROUTE_TO_PAGE_ID_SUCCESS';
export const FETCH_ROUTE_TO_PAGE_ID_FAILURE = 'FETCH_ROUTE_TO_PAGE_ID_FAILURE';
export const ADD_ROUTE_TO_PAGE_ID_START = 'ADD_ROUTE_TO_PAGE_ID_START';
export const ADD_ROUTE_TO_PAGE_ID_SUCCESS = 'ADD_ROUTE_TO_PAGE_ID_SUCCESS';
export const ADD_ROUTE_TO_PAGE_ID_FAILURE = 'ADD_ROUTE_TO_PAGE_ID_FAILURE';
export const FETCH_ROUTE_TO_PAGE_IDS_START = 'FETCH_ROUTE_TO_PAGE_IDS_START';
export const FETCH_ROUTE_TO_PAGE_IDS_SUCCESS = 'FETCH_ROUTE_TO_PAGE_IDS_SUCCESS';
export const FETCH_ROUTE_TO_PAGE_IDS_FAILURE = 'FETCH_ROUTE_TO_PAGE_IDS_FAILURE';

// Forms

export const SUBMIT_FORM_REQUEST = 'SUBMIT_FORM_REQUEST,';
export const SUBMIT_FORM_SUCCESS = 'SUBMIT_FORM_SUCCESS,';
export const SUBMIT_FORM_FAILURE = 'SUBMIT_FORM_FAILURE,';

export const SUBMIT_CONTACT_US_FORM_REQUEST = 'SUBMIT_CONTACT_US_FORM_REQUEST';
export const SUBMIT_CONTACT_US_FORM_SUCCESS = 'SUBMIT_CONTACT_US_FORM_SUCCESS';
export const SUBMIT_CONTACT_US_FORM_FAILURE = 'SUBMIT_CONTACT_US_FORM_FAILURE';

export const ADD_REVIEW_REQUEST = 'ADD_REVIEW_REQUEST';
export const ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS';
export const ADD_REVIEW_FAILURE = 'ADD_REVIEW_FAILURE';

export const ADD_TESTIMONIAL_REQUEST = 'ADD_TESTIMONIAL_REQUEST';
export const ADD_TESTIMONIAL_SUCCESS = 'ADD_TESTIMONIAL_SUCCESS';
export const ADD_TESTIMONIAL_FAILURE = 'ADD_TESTIMONIAL_FAILURE';
export const CHECK_REVIEW_SUBMITTED = 'CHECK_REVIEW_SUBMITTED';
export const CHECK_TESTIMONIAL_SUBMITTED = 'CHECK_TESTIMONIAL_SUBMITTED';


//Chats 

export const CREATE_GROUP_CHAT_REQUEST = 'CREATE_GROUP_CHAT_REQUEST';
export const CREATE_GROUP_CHAT_SUCCESS = 'CREATE_GROUP_CHAT_SUCCESS';
export const CREATE_GROUP_CHAT_FAILURE = 'CREATE_GROUP_CHAT_FAILURE';

//Tickets Dashboard


export const FETCH_TICKETS_DASHBOARD_HEADER_DATA_REQUEST = 'FETCH_TICKETS_DASHBOARD_HEADER_DATA_REQUEST'
export const FETCH_TICKETS_DASHBOARD_HEADER_DATA_SUCCESS = 'FETCH_TICKETS_DASHBOARD_HEADER_DATA_SUCCESS'
export const FETCH_TICKETS_DASHBOARD_HEADER_DATA_FAILURE = 'FETCH_TICKETS_DASHBOARD_HEADER_DATA_FAILURE'
export const GET_TICKET_DETAILS_FAILURE = 'GET_TICKET_DETAILS_FAILURE'
export const UPDATE_TICKET_DETAILS_FAILURE = 'UPDATE_TICKET_DETAILS_FAILURE'
export const GET_TICKET_DETAILS_REQUEST = 'GET_TICKET_DETAILS_REQUEST'
export const UPDATE_TICKET_DETAILS_REQUEST = 'UPDATE_TICKET_DETAILS_REQUEST'
export const GET_TICKET_DETAILS_SUCCESS = 'GET_TICKET_DETAILS_SUCCESS'
export const UPDATE_TICKET_DETAILS_SUCCESS = 'UPDATE_TICKET_DETAILS_SUCCESS'
export const ADD_COMMENT_TO_TICKET_REQUEST = 'ADD_COMMENT_TO_TICKET_REQUEST'
export const ADD_COMMENT_TO_TICKET_SUCCESS = 'ADD_COMMENT_TO_TICKET_SUCCESS'
export const ADD_COMMENT_TO_TICKET_FAILURE = 'ADD_COMMENT_TO_TICKET_FAILURE'

export const FETCH_USER_SIGNUP_LOGS_SUCCESS = 'FETCH_USER_SIGNUP_LOGS_SUCCESS';
export const FETCH_USER_SIGNUP_LOGS_ERROR = 'FETCH_USER_SIGNUP_LOGS_ERROR';
export const UPDATE_USER_SIGNUP_LOG = 'UPDATE_USER_SIGNUP_LOG';



//templates


export const GET_TEMPLATES_REQUEST = "GET_TEMPLATES_REQUEST";
export const GET_TEMPLATES_SUCCESS = "GET_TEMPLATES_SUCCESS";
export const GET_TEMPLATES_FAILURE = "GET_TEMPLATES_FAILURE";
export const GET_TEMPLATE_REQUEST = "GET_TEMPLATE_REQUEST";
export const GET_TEMPLATE_SUCCESS = "GET_TEMPLATE_SUCCESS";
export const GET_TEMPLATE_FAILURE = "GET_TEMPLATE_FAILURE";
export const ADD_TEMPLATE_REQUEST = "ADD_TEMPLATE_REQUEST";
export const ADD_TEMPLATE_SUCCESS = "ADD_TEMPLATE_SUCCESS";
export const ADD_TEMPLATE_FAILURE = "ADD_TEMPLATE_FAILURE";
export const EDIT_TEMPLATE_REQUEST = "EDIT_TEMPLATE_REQUEST";
export const EDIT_TEMPLATE_SUCCESS = "EDIT_TEMPLATE_SUCCESS";
export const EDIT_TEMPLATE_FAILURE = "EDIT_TEMPLATE_FAILURE";
export const DELETE_TEMPLATE_REQUEST = "DELETE_TEMPLATE_REQUEST";
export const DELETE_TEMPLATE_SUCCESS = "DELETE_TEMPLATE_SUCCESS";
export const DELETE_TEMPLATE_FAILURE = "DELETE_TEMPLATE_FAILURE";
export const FILE_UPLOAD_SUCCESS = "FILE_UPLOAD_SUCCESS";
export const FILE_UPLOAD_PROGRESS = "FILE_UPLOAD_PROGRESS";

export const DELETE_CAROUSEL_ITEM_REQUEST = 'DELETE_CAROUSEL_ITEM_REQUEST';
export const DELETE_CAROUSEL_ITEM_SUCCESS = 'DELETE_CAROUSEL_ITEM_SUCCESS';
export const DELETE_CAROUSEL_ITEM_FAILURE = 'DELETE_CAROUSEL_ITEM_FAILURE';

export const EDIT_CAROUSEL_ITEM_REQUEST = 'EDIT_CAROUSEL_ITEM_REQUEST';
export const EDIT_CAROUSEL_ITEM_SUCCESS = 'EDIT_CAROUSEL_ITEM_SUCCESS';
export const EDIT_CAROUSEL_ITEM_FAILURE = 'EDIT_CAROUSEL_ITEM_FAILURE';

// blogs 

export const SET_BLOG_AUTHOR = "SET_BLOG_AUTHOR";
export const TRENDING_BLOGS_REQUEST = 'TRENDING_BLOGS_REQUEST';
export const TRENDING_BLOGS_FAILURE = 'TRENDING_BLOGS_FAILURE';
export const TRENDING_BLOGS_SUCCESS = 'TRENDING_BLOGS_SUCCESS';
export const GET_TOTAL_BLOGS_REQUEST = 'GET_TOTAL_BLOGS_REQUEST';
export const GET_TOTAL_BLOGS_SUCCESS = 'GET_TOTAL_BLOGS_SUCCESS';
export const GET_TOTAL_BLOGS_FAILURE = 'GET_TOTAL_BLOGS_FAILURE';
export const GET_TOTAL_BLOGS_LIST_REQUEST = 'GET_TOTAL_BLOGS_LIST_REQUEST';
export const GET_TOTAL_BLOGS_LIST_FAILURE = 'GET_TOTAL_BLOGS_LIST_FAILURE';
export const GET_TOTAL_BLOGS_LIST_SUCCESS = 'GET_TOTAL_BLOGS_LIST_SUCCESS';
export const GET_BLOGS_REQUEST = 'GET_BLOGS_REQUEST';
export const GET_BLOGS_SUCCESS = 'GET_BLOGS_SUCCESS';
export const GET_BLOGS_FAILURE = 'GET_BLOGS_FAILURE';
export const SEARCH_BLOGS_REQUEST = 'SEARCH_BLOGS_REQUEST';
export const SEARCH_BLOGS_SUCCESS = 'SEARCH_BLOGS_SUCCESS';
export const SEARCH_BLOGS_FAILURE = 'SEARCH_BLOGS_FAILURE';
export const SEARCH_BLOGS = 'SEARCH_BLOGS';
export const APPEND_BLOGS = 'APPEND_BLOGS';
export const BLOGS_LIMIT_SET = "BLOGS_LIMIT_SET";
export const HIDE_MORE_BUTTON = "HIDE_MORE_BUTTON";
export const GET_BLOG_DETAILS_REQUEST = 'GET_BLOG_DETAILS_REQUEST';
export const GET_BLOG_DETAILS_FAILURE = 'GET_BLOG_DETAILS_FAILURE';
export const GET_BLOG_DETAILS_SUCCESS = 'GET_BLOG_DETAILS_SUCCESS';
export const SET_TAGS_REQUEST = 'SET_TAGS_REQUEST';
export const SET_TAGS_FAILURE = 'SET_TAGS_FAILURE';
export const SET_TAGS_SUCCESS = 'SET_TAGS_SUCCESS';
export const SET_CATEGORIES_REQUEST = 'SET_CATEGORIES_REQUEST';
export const SET_CATEGORIES_FAILURE = 'SET_CATEGORIES_FAILURE';
export const SET_CATEGORIES_SUCCESS = 'SET_CATEGORIES_SUCCESS';
export const SET_COMMENTS_REQUEST = 'SET_COMMENTS_REQUEST';
export const SET_COMMENTS_FAILURE = 'SET_COMMENTS_FAILURE';
export const SET_COMMENTS_SUCCESS = 'SET_COMMENTS_SUCCESS';
export const SET_LIKES_REQUEST = 'SET_LIKES_REQUEST';
export const SET_LIKES_FAILURE = 'SET_LIKES_FAILURE';
export const SET_LIKES_SUCCESS = 'SET_LIKES_SUCCESS';
export const ADD_BLOG_REQUEST = 'ADD_BLOG_REQUEST';
export const ADD_BLOG_SUCCESS = 'ADD_BLOG_SUCCESS';
export const ADD_BLOG_FAILURE = 'ADD_BLOG_FAILURE';
export const EDIT_BLOG_REQUEST = 'EDIT_BLOG_REQUEST';
export const EDIT_BLOG_SUCCESS = 'EDIT_BLOG_SUCCESS';
export const EDIT_BLOG_FAILURE = 'EDIT_BLOG_FAILURE';
export const DELETE_BLOG_REQUEST = 'DELETE_BLOG_REQUEST';
export const DELETE_BLOG_SUCCESS = 'DELETE_BLOG_SUCCESS';
export const DELETE_BLOG_FAILURE = 'DELETE_BLOG_FAILURE';
export const ADD_DELETED_BLOG_REQUEST = 'ADD_DELETED_BLOG_REQUEST';
export const ADD_DELETED_BLOG_SUCCESS = 'ADD_DELETED_BLOG_SUCCESS';
export const ADD_DELETED_BLOG_FAILURE = 'ADD_DELETED_BLOG_FAILURE';
export const ADD_LIKE = 'ADD_LIKE';
export const REMOVE_LIKE = "REMOVE_LIKE";
export const ADD_COMMENT = 'ADD_COMMENT';
export const REMOVE_COMMENT = "REMOVE_COMMENT";
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const SET_COMMENTS = "SET_COMMENTS";
export const SET_RELATED_BLOGS = "SET_RELATED_BLOGS";
export const SET_RECENT_BLOGS = "SET_RECENT_BLOGS";
export const PROFILE_IMAGE_CHANGE = "PROFILE_IMAGE_CHANGE";
export const SET_TAGS = "SET_TAGS";
export const SET_CATEGORIES = "SET_CATEGORIES";
export const GET_SENT_TO_REVIEW_TOTAL_BLOGS_REQUEST = 'GET_SENT_TO_REVIEW_TOTAL_BLOGS_REQUEST';
export const GET_SENT_TO_REVIEW_TOTAL_BLOGS_SUCCESS = 'GET_SENT_TO_REVIEW_TOTAL_BLOGS_SUCCESS';
export const GET_SENT_TO_REVIEW_TOTAL_BLOGS_FAILURE = 'GET_SENT_TO_REVIEW_TOTAL_BLOGS_FAILURE';
// export const GET_BLOG_DETAILS_REQUEST = 'GET_BLOG_DETAILS_REQUEST';
export const REDIRECT_REQUEST = "REDIRECT_REQUEST";
export const CLEAR_REDIRECT = "CLEAR_REDIRECT";
export const REDIRECT_SUCCESS = "REDIRECT_SUCCESS";
export const REDIRECT_FAILURE = "REDIRECT_FAILURE";
export const FETCH_BLOGS_BY_TIME_RANGE_REQUEST = 'FETCH_BLOGS_BY_TIME_RANGE_REQUEST';
export const FETCH_BLOGS_BY_TIME_RANGE_SUCCESS = 'FETCH_BLOGS_BY_TIME_RANGE_SUCCESS';
export const FETCH_BLOGS_BY_TIME_RANGE_FAILURE = 'FETCH_BLOGS_BY_TIME_RANGE_FAILURE';
 


// Portfolio

export const ADD_EDUCATION_START = 'ADD_EDUCATION_START';
export const ADD_EDUCATION_SUCCESS = 'ADD_EDUCATION_SUCCESS';
export const ADD_EDUCATION_FAILURE = 'ADD_EDUCATION_FAILURE';


export const EDIT_EDUCATION_START = 'EDIT_EDUCATION_START';
export const EDIT_EDUCATION_SUCCESS = 'EDIT_EDUCATION_SUCCESS';
export const EDIT_EDUCATION_FAILURE = 'EDIT_EDUCATION_FAILURE';

export const ADD_CERTIFICATION_REQUEST = 'ADD_CERTIFICATION_REQUEST';
export const ADD_CERTIFICATION_SUCCESS = 'ADD_CERTIFICATION_SUCCESS';
export const ADD_CERTIFICATION_FAILURE = 'ADD_CERTIFICATION_FAILURE';

export const UPDATE_CERTIFICATION_REQUEST = 'UPDATE_CERTIFICATION_REQUEST';
export const UPDATE_CERTIFICATION_SUCCESS = 'UPDATE_CERTIFICATION_SUCCESS';
export const UPDATE_CERTIFICATION_FAILURE = 'UPDATE_CERTIFICATION_FAILURE';

export const DELETE_CERTIFICATION_REQUEST = 'DELETE_CERTIFICATION_REQUEST';
export const DELETE_CERTIFICATION_SUCCESS = 'DELETE_CERTIFICATION_SUCCESS';
export const DELETE_CERTIFICATION_FAILURE = 'DELETE_CERTIFICATION_FAILURE';
export const GET_CERTIFICATION_LIST_REQUEST = 'GET_CERTIFICATION_LIST_REQUEST';
export const GET_CERTIFICATION_LIST_SUCCESS = 'GET_CERTIFICATION_LIST_SUCCESS';
export const GET_CERTIFICATION_LIST_FAILURE = 'GET_CERTIFICATION_LIST_FAILURE';